# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: redis-deployment
#   labels:
#     name: redis-deployment
#     app: demo-voting-app
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       name: redis
#       app: demo-voting-app
#   template:
#     metadata:
#       labels:
#         name: redis
#         app: demo-voting-app
#     spec:
#       containers:
#       - name: redis
#         image: redis
#         ports:
#         - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    name: redis
    app: demo-voting-app
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      name: redis
      app: demo-voting-app
  template:
    metadata:
      labels:
        name: redis
        app: demo-voting-app
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
          name: redis
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pvc
  volumeClaimTemplates:
  - metadata:
      name: redis-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
